import {
  HelpProse,
  Callout,
  Steps,
  Step,
  DashboardLink,
} from "@/components/feature/help/HelpProse";
import type { HelpArticleMeta } from "@/content/help/types";

export const meta: HelpArticleMeta = {
  slug: "two-factor-authentication-setup",
  title: "Two-factor authentication setup",
  shortDescription:
    "Optional for seekers but strongly recommended. TOTP app + backup codes; what happens when you lose your phone; how to disable.",
  category: "account",
  keywords: [
    "2fa",
    "two-factor",
    "totp",
    "authenticator",
    "backup codes",
    "security",
    "google authenticator",
    "1password",
  ],
  related: [
    "resetting-your-password",
    "deleting-your-account-right-to-erasure",
  ],
  surfaceLink: "/dashboard/account",
  updatedAt: "2026-05-29",
};

export default function Article() {
  return (
    <HelpProse>
      <p>
        Two-factor authentication (2FA) adds a second check at sign-in
        beyond your password. On Sebenza, 2FA uses TOTP &mdash;
        time-based codes generated by an authenticator app (Google
        Authenticator, 1Password, Authy, etc.). It&rsquo;s optional for
        seekers and strongly recommended &mdash; the platform holds
        your work history, qualifications, and contact preferences,
        which collectively is worth protecting.
      </p>

      <h2>Setting it up</h2>
      <Steps>
        <Step number={1}>
          <p>
            On the Account page, find the <em>Two-factor authentication</em>
            panel. Hit <strong>Enable 2FA</strong>. A modal opens with
            a QR code.
          </p>
        </Step>
        <Step number={2}>
          <p>
            Open your authenticator app and scan the QR code. The app
            starts generating 6-digit codes that rotate every 30
            seconds.
          </p>
        </Step>
        <Step number={3}>
          <p>
            Back on the panel, type the current 6-digit code from your
            app and confirm. The platform verifies and enables 2FA.
          </p>
        </Step>
        <Step number={4}>
          <p>
            Download the <strong>backup codes</strong> the platform
            shows you next. Eight one-time codes. Store them somewhere
            you can find without your phone (password manager,
            printed-and-locked-away, encrypted file). Each one works
            once if you lose access to your authenticator app.
          </p>
        </Step>
      </Steps>

      <Callout type="warning" title="Backup codes are the recovery path">
        <p>
          If you lose your phone and don&rsquo;t have backup codes, the
          recovery path is a manual support process: we verify your
          identity against the data we already hold (name, email,
          national ID where on file). It works, but takes 13 working
          days and is much more painful than just having the backup
          codes on hand. Save them.
        </p>
      </Callout>

      <h2>Signing in with 2FA on</h2>
      <p>
        After enabling, every sign-in asks for your password, then your
        current TOTP code. Sessions stay open for the standard 30 days
        per device; you don&rsquo;t enter the TOTP every time you load
        a page, only at sign-in.
      </p>

      <h2>Disabling 2FA</h2>
      <p>
        From the same panel, hit <strong>Disable 2FA</strong> &mdash;
        the platform asks for your current TOTP code as confirmation
        and writes an audit row. Disabling is a real downgrade in
        account security; do it deliberately and only if you have a
        specific reason (switching to a different MFA method, for
        example, when the platform supports it).
      </p>

      <DashboardLink href="/dashboard/account">Open account settings</DashboardLink>
    </HelpProse>
  );
}
