/**
 * Phase 9 — robots.txt generated by Next.
 *
 * Allow indexing of the public marketing + analytics + profile surfaces.
 * Disallow every authenticated workspace (dashboard, employer, admin,
 * gov) and every API route. The `/api/insights/outcomes/export` route
 * IS public (audit-logged) but we keep it out of search-engine indexes
 * anyway because a CSV is a download, not a destination.
 */

import type { MetadataRoute } from "next";

const appUrl = process.env.BETTER_AUTH_URL ?? "https://sebenza.co.za";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: [
          "/api/",
          "/dashboard",
          "/dashboard/",
          "/employer",
          "/employer/",
          "/admin",
          "/admin/",
          "/gov",
          "/gov/",
          "/sign-in",
          "/sign-up",
          "/setup-2fa",
          "/verify-2fa",
          "/verify-email",
          "/forgot-password",
          "/reset-password",
        ],
      },
    ],
    sitemap: `${appUrl}/sitemap.xml`,
  };
}
