/**
 * Phase 9  robots.txt generated by Next. Phase 33 pass:
 *
 *   - Base URL from `lib/seo.ts` (D1  one source of truth).
 *   - Private paths are expanded across the locale prefixes: the old
 *     list only covered the unprefixed forms, leaving `/zu/dashboard`,
 *     `/af/sign-in` etc. crawlable. next-intl's `as-needed` prefix
 *     means every private surface exists at 1 + 3 URLs.
 *
 * Allow indexing of the public marketing + analytics + profile surfaces.
 * Disallow every authenticated workspace (dashboard, employer, admin,
 * gov) and every API route. The `/api/insights/outcomes/export` route
 * IS public (audit-logged) but we keep it out of search-engine indexes
 * anyway because a CSV is a download, not a destination.
 *
 * robots.txt prevents CRAWLING, not indexing of a leaked URL itself
 * the route-group layouts additionally emit `noindex` metadata (33.6).
 */

import type { MetadataRoute } from "next";
import { routing } from "@/i18n/routing";
import { SITE_URL } from "@/lib/seo";

const PRIVATE_PATHS = [
  "/dashboard",
  "/dashboard/",
  "/employer",
  "/employer/",
  "/admin",
  "/admin/",
  "/gov",
  "/gov/",
  "/sign-in",
  "/sign-up",
  "/setup-2fa",
  "/verify-2fa",
  "/verify-email",
  "/forgot-password",
  "/reset-password",
];

export default function robots(): MetadataRoute.Robots {
  const nonDefaultLocales = routing.locales.filter(
    (l) => l !== routing.defaultLocale,
  );
  const disallow = [
    "/api/",
    ...PRIVATE_PATHS,
    ...nonDefaultLocales.flatMap((l) => PRIVATE_PATHS.map((p) => `/${l}${p}`)),
  ];

  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
